// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7M6tWIpghJ-q-sLcD6ueJUUFMLPVacRg',
    appId: '1:228792292130:web:08ee664710880a3e564b7b',
    messagingSenderId: '228792292130',
    projectId: 'infodisplay-25291',
    authDomain: 'infodisplay-25291.firebaseapp.com',
    storageBucket: 'infodisplay-25291.firebasestorage.app',
    measurementId: 'G-XBMR4374PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsVmh30Bg0HO6pVp4VtKK66yFmpNBet-w',
    appId: '1:228792292130:android:cae7c8ca009aad86564b7b',
    messagingSenderId: '228792292130',
    projectId: 'infodisplay-25291',
    storageBucket: 'infodisplay-25291.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLlYd16TE4JAvt6Rr2CwvwM_yJmtfTpM0',
    appId: '1:228792292130:ios:0f1b4e53a209b62c564b7b',
    messagingSenderId: '228792292130',
    projectId: 'infodisplay-25291',
    storageBucket: 'infodisplay-25291.firebasestorage.app',
    iosBundleId: 'com.example.infodisplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLlYd16TE4JAvt6Rr2CwvwM_yJmtfTpM0',
    appId: '1:228792292130:ios:0f1b4e53a209b62c564b7b',
    messagingSenderId: '228792292130',
    projectId: 'infodisplay-25291',
    storageBucket: 'infodisplay-25291.firebasestorage.app',
    iosBundleId: 'com.example.infodisplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7M6tWIpghJ-q-sLcD6ueJUUFMLPVacRg',
    appId: '1:228792292130:web:0fad5eb638354d57564b7b',
    messagingSenderId: '228792292130',
    projectId: 'infodisplay-25291',
    authDomain: 'infodisplay-25291.firebaseapp.com',
    storageBucket: 'infodisplay-25291.firebasestorage.app',
    measurementId: 'G-X0Q2M7Z3EX',
  );
}
